services:

  service:
    image: product-service:latest
    container_name: product-service
    environment:
      DEBUG_PORT: ${DEBUG_PORT}
    ports:
      - "${TLS_PORT}:${TLS_PORT}"
      - "${N_TLS_PORT}:${N_TLS_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: product-service-db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: